# pyproject.toml

[project]
name = "socialgaze"
version = "0.1.0"
description = "Naturalistic social gaze and neural data analysis pipeline"
authors = [{name = "Prabaha Gangopadhyay"}]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
